spring:
  application:
    name: api-gateway

server:
  port: 9999

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  routes:
    user:
      #url: http://localhost:8080/api/v1/user
      path: /user-api/**
      serviceId: user-service
    product:
      #url: http://localhost:8081/api/v1/product
      path: /product-api/**
      serviceId: product-service